services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

    volumes:
      - jrdata:/var/lib/postgresql/data

volumes:
  jrdata:
